// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test3Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test3() {
    driver.Navigate().GoToUrl("https://www.finexbox.com/html/xway.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.Id("email")).Click();
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("email")).SendKeys("odin@dir.bg");
    driver.FindElement(By.Id("pwd")).SendKeys("Eraser7107");
    driver.SwitchTo().Frame(0);
    driver.FindElement(By.CssSelector(".recaptcha-checkbox-border")).Click();
    driver.SwitchTo().DefaultContent();
    driver.SwitchTo().Frame(1);
    driver.FindElement(By.CssSelector("tr:nth-child(1) > .rc-imageselect-tile:nth-child(3) .rc-image-tile-33")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33")).Click();
    driver.FindElement(By.Id("recaptcha-verify-button")).Click();
    {
      var element = driver.FindElement(By.Id("recaptcha-verify-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(4) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-44")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) > .rc-imageselect-tile:nth-child(4) .rc-image-tile-44")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-44")).Click();
    driver.FindElement(By.Id("recaptcha-verify-button")).Click();
    driver.FindElement(By.CssSelector(".rc-imageselect-incorrect-response")).Click();
    driver.FindElement(By.CssSelector(".rc-imageselect-incorrect-response")).Click();
  }
}
